### ISSUE TITLE
Compile version 2.1.10

### ISSUE THREAD

**Issue by hazedine** [BIC-MNI/minc#4]
Hi, 
I am unsuccessful to build the MINC version 2.1.10. There is an error with the file hdf_convenience.c:

`/hydra/home/hassemlal/work/minc/libsrc/hdf_convenience.c: In function ‘hdf_put_dimorder’:
/hydra/home/hassemlal/work/minc/libsrc/hdf_convenience.c:621: error: too many arguments to function ‘H5Acreate1’
/hydra/home/hassemlal/work/minc/libsrc/hdf_convenience.c: In function ‘hdf_set_length’:
/hydra/home/hassemlal/work/minc/libsrc/hdf_convenience.c:928: error: too many arguments to function ‘H5Acreate1’
/hydra/home/hassemlal/work/minc/libsrc/hdf_convenience.c: In function ‘hdf_attput’:
/hydra/home/hassemlal/work/minc/libsrc/hdf_convenience.c:1110: warning: cast to pointer from integer of different size
/hydra/home/hassemlal/work/minc/libsrc/hdf_convenience.c:1189: error: too many arguments to function ‘H5Acreate1’
/hydra/home/hassemlal/work/minc/libsrc/hdf_convenience.c: In function ‘hdf_copy_attr’:
/hydra/home/hassemlal/work/minc/libsrc/hdf_convenience.c:2054: warning: cast from pointer to integer of different size
/hydra/home/hassemlal/work/minc/libsrc/hdf_convenience.c:2071: error: too many arguments to function ‘H5Acreate1’
make[2]: *** [CMakeFiles/minc2.dir/libsrc/hdf_convenience.c.o] Error 1
make[1]: *** [CMakeFiles/minc2.dir/all] Error 2`

I can build version 2.1.00 without problems. I'm using ubuntu lucid with libhdf5-serial-1.8.4-5.

**Comment by vfonov** [comment]
I see no problems compiling on Ubuntu 11.04 32 bit using 

libhdf5-serial-1.8.4   1.8.4-patch1-2ubuntu3
libhdf5-serial-dev     1.8.4-patch1-2ubuntu3
libnetcdf-dev           1:4.1.1-5build1
libnetcdf6               1:4.1.1-5build1

after running ./configure --prefix=$HOME/minc

**Comment by hazedine** [comment]
I forgot to mention that I was compiling the project with CMake. The CMakeCache.txt is available at https://gist.github.com/1886204

**Comment by vfonov** [comment]
Ok, I found the suorce of the error - the CMake version of configuration doesn't define H5Acreate_vers, so to solve it 
one should add "#define H5Acreate_vers 2" in config.h.cmake

**Comment by andrewjanke** [comment]
Thanks Vlad, he had me worried for a bit there until I saw the CMAKE bit.....

For reference, this line is here in configure.in

```
 https://github.com/andrewjanke/minc/blob/master/configure.in#L54
```

**Comment by hazedine** [comment]
It works now. Thanks vlad :)
